- src/js/utils/charts.js
- This fixes the legend overlapping for the land cover loss png export of the chart
> Legend fixes in highcharts

- src/index.pug
This is so users would only have to change the `_app.base` url instead of also having to change the linked css files in the `<head>`
> Load css from app base instead of hardcoded relative path

- src/js/utils/AppUtils.js
When we switch the build process to webpack we changed up the file structure of our hosted files. It used to be `.../v1.1.x/1.1.x/`, we dropped the redundantly named file and it is now just `.../v1.1.x/`.
> use correct base when opening report

- src/css/legendPanel.styl
to prevent icon from shrinking with long text in IE.
> add min-width for legend-icon class

- src/js/components/LegendPanel/WebMapFeatureLayerLegend.js
- [Duplicate AGOL Legend Items](https://blueraster.assembla.com/spaces/WRI_Forest_Atlas/tickets/realtime_list?ticket=788) --> Testable on [beta](https://beta.blueraster.io/mapbuilder/788-agol-duplicate-legends/?appid=277b92455c6c49059a95c9129be7baf9)
> No duplicate symbols in featureLayer legends

- src/js/components/Map.js
Addresses #257 and can be tested here: [https://beta.blueraster.io/mapbuilder/257-legend-visible/external.html?l=en](https://beta.blueraster.io/mapbuilder/257-legend-visible/external.html?l=en)
This fixes the hidden legend issue when loading an app from its alternate language via url hash
> Updated our mapLoaded to show legend when switching maps

- src/css/layerPanel.styl
- src/css/modal.styl
- src/js/components/LayerPanel/LayerCheckbox.js
Satellite Imagery btn: https://github.com/wri/gfw-mapbuilder/issues/297
Change top of satellite imagery modal: https://github.com/wri/gfw-mapbuilder/issues/298
Can be tested here: http://alpha.blueraster.io/gfw-mapbuilder/297-298-imagery-css-fixes/external.html
> Hot Fix: CSS fixes for Satellite Imagery

- src/external.pug
Test this fix [here](http://alpha.blueraster.io/gfw-mapbuilder/333-share-break/external.html?appid=277b92455c6c49059a95c9129be7baf9) and see why this is broken via [this](url) commit (we changed our `id` and now our `domClass.remove` call won't work!
> Reverted share-modal id

- src/js/utils/analysisUtils.js
Addresses the old #316 in certain use cases, testable (with proper `appid`) [here](https://alpha.blueraster.io.s3.amazonaws.com/gfw-mapbuilder/316-geometry-catch/external.html?appid=0bdf18459d5544e881a06577805f2b8f)
> Updated catch on geometry registration

- cypress/integration/test_spec.js
- cypress/integration/ui-workflows.js
- package.json
Let's get our end-to-end tests up to date with our unit tests! One day, I want to have these `e2e` tests running the same logic/workflows across all of the deployed Mapbuilder apps that point to the latest version of our library: Georgia Atlas, Ethiopia Restoration Atlas, Cameroon Forest Atlas, Tierra Indigenous Platform, the V1 latest/base configuration, etc
> Unit test update

- src/js/report/report.js
https://github.com/wri/gfw-mapbuilder/issues/246#issuecomment-502263769
Now the report no longer inherits old `analysisModules`! You can test this on previously-deployed apps: 
https://my.gfw-mapbuilder.org/v1.4.0/ and http://blueraster.teaches-yoga.com/CMR?l=en
> No more analysis modules in report localStorage

- src/css/report.styl
- src/external.pug
- src/externalReport.pug
- src/js/components/AnalysisPanel/VegaChart.js
- src/js/report/ReportAnalysis.js
#436 
http://alpha.blueraster.io/gfw-mapbuilder/436-smaller-max-width/
@SwampGuzzler This is more than likely still a WIP. Once Richard updates the signals by not hardcoding heights and widths, then I can adjust the max-width on the div container wrapping each of the chart widgets accordingly to make it look nice. Right now, I just chose a `max-width` value of 500px for the badge charts to demonstrate that `max-width` works (see my conversation with Richard in the ticket!)
Also, this will need to be merged into #396 which has now become the base branch for all resizing tickets!
> 436 smaller max width

- src/js/stores/MapStore.js
Porting [this](https://github.com/wri/gfw-mapbuilder/commit/f1aac1acfb0defe95d7e66400cbdca597a143e73) error-check over from WCS - if the geometry that the User has selected is in a different spatial reference, the GFW API's `geostore` won't play nicely with an exact version of that geometry that we get back from the Server, so instead let's just use the original geometry.
> Allowing any spatialRefs when registering geoms w/ the geostore

- src/resources.js
@SwampGuzzler The extra trailing comma accidentally got merged in again from the last PR that updated the `eslintrc` 😱
> Remove that extra trailing comma again!

- src/css/report.styl
https://github.com/wri/gfw-mapbuilder/issues/494
http://alpha.blueraster.io/gfw-mapbuilder/494-download-buttons-not-in-right-location/
> Add max width onto vega-chart_container

- src/css/modal.styl
#500 
http://alpha.blueraster.io/gfw-mapbuilder/500-add-tree-cover-density-svg/
> Add missing background css rule to tree-icon and forest-icon

- src/js/actions/MapActions.js
- src/js/components/Map.js
- src/js/components/Modals/ImageryModal.js
- src/js/stores/MapStore.js
This fix removes the Tooltip that provides data on-hover when the image does not display properly --> https://github.com/wri/gfw-mapbuilder/issues/483#issuecomment-527633970
Test [here!](http://alpha.blueraster.io/gfw-mapbuilder/483-satellite-mouseover/)
> Handling satellite errors w/ no mouseover

- src/external.pug
- src/externalReport.pug
- src/js/components/AnalysisPanel/VegaChart.js
- src/js/utils/charts.js
- src/resources.js
@SwampGuzzler An import of `vega` in `charts.js` is missing, resulting in our analysis charts failing to render in the analysis panel! I noticed this was happening in any config, not just this specific Kenya one mentioned in the ticket.
Other configs worked when I added this import statement in. But for the Kenya build, it appears this is specific to its geostore that it's using since it keeps returning with a status code of 500.
Build in case we need it: http://alpha.blueraster.io/gfw-mapbuilder/567-analysis-not-loading-using-map-geometries/
> 567 analysis not loading using map geometries

- src/css/infoWindow.styl
- src/css/tabButtons.styl
- src/js/components/TabPanel/TabButtons.js
- src/resources.js
@SwampGuzzler Noticed some more styling issues. The colored dot that appears on the active analysis and documents was positioned incorrectly when there are less than 5 tabs, like in the default resources. I moved them so that they could use `absolute`/ `relative` positioning correctly. Also added another check to hide the documents dot if there is no documents tab. Finally, added some margin to the custom feature name so it's not pushed against the edit/delete buttons.
For reference:
> Tab button adjustments

- src/js/components/AnalysisPanel/MeasurementTool.js
Test-able here [http://blueraster.teaches-yoga.com/CMR?l=en](http://blueraster.teaches-yoga.com/CMR?l=en)
Right now we are not registering **geometries** to the `geostore` on initial click. This is because we are not entering any of the `if` statements in the `infoWindowUpdated` function because we don't have a `brApp.map.measurement`. This fix is to get that `measurement` registered on `language-change`!!
- On `language-change`, we create a new **measurement** tool, and add it to the **brApp.map**
- We hide the domNode of the **old** tool
> Flexibly attaching measurement on language-change

- src/js/report/ReportTable.js
- src/js/utils/AppUtils.js
- src/resources.js
Issue Number: #628 
- Adds the `mapLayerId` to URLs generated in the CMS in order to retrieve the table attribute data.
-
-
This is a CMS specific issue and needs to be tested out!
> 628 table attribute table

- package-lock.json
- package.json
- src/js/components/App.tsx
- src/js/constants/actionTypes.js
- src/js/controllers/mapController.ts
- src/js/index.tsx
- src/js/reducers/app.js
- src/js/reducers/mapview/actions.js
- src/js/reducers/mapview/index.js
- src/js/reducers/mapview/loadError.js
- src/js/store/mapview/types.ts
- Installed `@types/react-redux` to integrate TSlinting with Redux
- Established a `MapviewStore` TS interface documenting all properties of Redux store
- `index.tsx` updated to leverage `Provider` and make Redux store available, app-wide
- `App.tsx` leverages Redux hooks to hook into state and conditionally manage content. Largely exists to confirm store is updating
- Created a new actionType, `MAP_ERROR` in `actionTypes.js`
- `initializeMap()` in `mapController.ts` was updated to include error-handling logic
- Refactored `mapReady` property of `mapview.js` reducer to be `isMapReady` reducer
- Created `loadError` reducer to architect structure of Redux store
- `app.js` reducer combines all reducers into a store, which is then imported into `store.js`
- Refactored actionCreator …
> Redux architecture, provider & store

- src/js/components/App.tsx
- src/js/components/mapview/Mapview.tsx
- tsconfig.json
- webpack.common.js
Webpack/Typescript out of the box does not recognize relative paths, we end up importing components like this : `../../../components/Modal`.
Adding aliases to `webpack` and `tsconfig` allows us more straightforward approach to importing like this:
`js/components/Modal`
> Implementation of path aliases

- src/js/components/mapview/Mapview.tsx
- src/js/controllers/mapController.ts
- src/js/store/appSettings/actions.ts
- src/js/store/appSettings/reducers.ts
- src/js/store/appSettings/types.ts
- src/js/store/appState/actions.ts
- src/js/store/appState/reducers.ts
- src/js/store/appState/types.ts
- src/js/store/index.ts
- Adding third redux store, so far we have:
1. `mapview` store (holds things related to map only)
2. `appSettings` store (basically our resources.js)
3. `appState` store (any dynamic values that get changed as user interacts with the app, modal open closed, panels toggled, active layers etc)
> Adding new redux store and renaming the old one

- configs/dojoConfig.ts
Updated version --> Let's figure out how to tie in the `@arcgis/webpack-plugin` module version with this `dojoConfig.ts` version variable
> Upped JS API to 4.14 in dojoConfig

- src/css/header.scss
- src/css/index.scss
- src/css/mapWidgets.scss
- src/css/modalCard.scss
- src/css/variables.scss
- src/js/components/mapWidgets/mapWidgets.tsx
- src/js/components/modal/modalCard.tsx
**Styling the modal card**
- `.modal-card-container` in `modalCard.scss` is centers on mobile/desktop consistently to account for changes to width/height. Media query was added to support centering/sizing on mobile devices
- deleted `.print-modal`, `.share-modal`, `.pen-modal` and `.search-modal` since they were no longer needed
- removed `setModalClassName()` from `modalCard.tsx` since the modal card will have a fixed width/height
**SASS variables file**
- `variables.scss` stores all SASS variables, organized into types (color, dimensions, etc)
- `header.scss`, `mapWidgets.scss`, `index.scss` and `modalCard.scss` use SASS variables via importing `variables.scss`
- removed unused SASS variables from `index.scss` since I was given the green light to centralize variables in …
> Ticket 713 - Modal sizing
