wri/gfw-mapbuilder

- src/js/components/AnalysisPanel/SadAlertsChart.js
- src/js/report/report.js
- src/report.jade
Added udpated analysis for Imazon Sad alerts to the report
> Added new analysis to the report

- .gitignore
- src/css/documentsPanel.styl
- src/css/layerPanel.styl
- src/css/timeWidget.styl
- src/js/components/LayerPanel/LayerPanel.js
- src/js/components/LayerPanel/TerraIControls.js
- src/js/components/Map.js
- src/js/components/MapControls/TimeWidget.js
- src/js/components/Modals/CanopyModal.js
- src/js/components/TabPanel/Documents.js
- src/js/languages.js
- src/js/utils/analysisUtils.js
- src/js/utils/rasterFunctions.js
- src/resources.js
Updated raster functions for slope analysis
Started on carbon biomass updates
Fixed issue with Above Ground Carbon Biomass Density support
Added more features to the TimeSlider
Edited the table in the documents tab
CSS fix for Calendar components on Chrome on Windows machines
Reset defaults in resources file
> Added new layer ordering

- src/css/footerInfo.styl
Fixes https://app.assembla.com/spaces/WRI_Forest_Atlas/tickets/realtime_list?ticket=617
> Sources now appear on the left of the coordinates in the footer

- src/css/variables.styl
- src/resources.js
- Updated the Landsat icon in the panel
> Landsat sprite

- src/index.jade
- src/js/config.js
- src/js/helpers/LayersHelper.js
- src/js/utils/analysisUtils.js
- src/locals.js
- src/resources.js
> Revert "Updating endpoints"

- config-panels/masterPanel.json
- src/js/languages.js
- src/resources.js
> Add georgian language

- config-panels/masterPanel.json
- src/js/components/Header.js
- src/js/components/Map.js
- src/js/components/MapControls/FooterInfos.js
> add ability to hide header and footer

- src/js/components/LayerPanel/LossControls.js
> Update url for forest loss tiles

- config-panels/masterPanel.json
- src/js/components/Header.js
- src/js/components/Map.js
- src/resources.js
@SwampGuzzler 
For ticket [654](https://app.assembla.com/spaces/WRI_Forest_Atlas/tickets/realtime_list?ticket=654)
> add ability to hide header and footer separately

- src/js/components/AnalysisPanel/Analysis.js
- src/js/components/AnalysisPanel/FiresBadge.js
- src/js/components/AnalysisPanel/TotalLossChart.js
- src/js/components/LayerPanel/GladControls.js
- src/js/components/Modals/CanopyModal.js
- src/js/components/Shared/ReportSubscribe.js
- src/js/config.js
- src/js/helpers/LayersHelper.js
- src/js/languages.js
- src/js/report/report.js
- src/js/utils/AppUtils.js
- src/js/utils/analysisUtils.js
- src/js/utils/charts.js
- src/js/utils/performAnalysis.js
- src/report.jade
> Update report layerdefs, charts, and canopy density

- src/js/components/AnalysisPanel/Analysis.js
- src/js/components/AnalysisPanel/BarChart.js
- src/js/components/AnalysisPanel/BiomassChart.js
- src/js/components/AnalysisPanel/LossGainBadge.js
- src/js/components/AnalysisPanel/TimeSeriesChart.js
- src/js/utils/analysisUtils.js
- src/js/utils/performAnalysis.js
> add errbacks and error states for when requests fail

- src/resources.js
I think we still need translations for [`languages.js`](https://github.com/wri/gfw-mapbuilder/blob/develop/src/js/languages.js#L223). So, maybe don't merge this yet until we find out if/when we will get that
> 665: Add georgian translations to resourses.js

- src/js/components/LayerPanel/LossControls.js
@SwampGuzzler Real quick one, to fix a bug I found with the timeslider
> fix timeslider when only one year selected

- src/js/actions/LayerActions.js
- src/js/components/LayerPanel/LayerGroup.js
- src/js/components/LayerPanel/LayerPanel.js
- src/js/components/LayerPanel/LayerRadio.js
- src/js/components/LegendPanel/LegendPanel.js
- src/js/stores/MapStore.js
* Also switch `Percentage land held` section from checkboxes to radios
> Fix radio button selection and visibility in legend

- src/js/components/LayerPanel/NestedCheckbox.js
- src/js/components/LegendPanel/LegendPanel.js
- src/js/components/LegendPanel/WebMapLegend.js
> re#330 update legend order to respect layer panel order

- src/js/components/LegendPanel/LegendPanel.js
- src/js/components/LegendPanel/WebMapLegend.js
- Fixes single layer legend display
You can test here http://alpha.blueraster.io/gfw-mapbuilder/676-agol-legend-single-layer/?appid=31fcf06895b34465b827d9ba8a4aac95
It also works with this http://alpha.blueraster.io/gfw-mapbuilder/676-agol-legend-single-layer/?appid=1270394ee49241a296390843733441f2
> Single layer from map service are now displayed correctly in the legend

- src/css/legendPanel.styl
- src/js/actions/MapActions.js
- src/js/components/LegendPanel/LayerLegend.js
- src/js/components/LegendPanel/LegendPanel.js
- src/js/components/LegendPanel/WebMapFeatureLayerLegend.js
- src/js/components/LegendPanel/WebMapLegend.js
- src/js/components/Map.js
@SwampGuzzler pretty confusing diff here, let me know if you have questions
> Add support for circles and lines in legend. Fix legend ordering

- src/js/actions/MapActions.js
[Build to test this change](http://alpha.blueraster.io/gfw-mapbuilder/704-tcl-drawing-order/)
> 704: sort layers before adding to map

- src/js/actions/LayerActions.js
- src/js/components/LayerPanel/LayerTransparency.js
- src/js/components/LegendPanel/LayerLegend.js
- src/js/components/LegendPanel/LegendPanel.js
- src/js/components/LegendPanel/WebMapFeatureLayerLegend.js
- src/js/components/LegendPanel/WebMapLegend.js
- src/js/components/Map.js
- src/js/stores/MapStore.js
* [Build with default map](http://alpha.blueraster.io/gfw-mapbuilder/710-legend-transparency/)
* [Build using a webmap with a bunch of different layer types](http://alpha.blueraster.io/gfw-mapbuilder/710-legend-transparency/?appid=e6e7369394804977b2bc6eb879e6088f)
> 710: Transfer layer transparency to the legend icon

- src/js/utils/basemapUtils.js
* [Bild for testing](http://alpha.blueraster.io/gfw-mapbuilder/706-basemap/?appid=345237536c8c4521bb4cba5332ac6126)
> add a check for World_Imagery Basemap

- src/css/tabButtons.styl
- src/js/actions/MapActions.js
- src/js/components/TabPanel/TabButtons.js
- src/js/stores/MapStore.js
* [Build to test this here](http://alpha.blueraster.io/gfw-mapbuilder/landmark-wait-for-geostore/)
> wait for geostore to finish before allowing analysis tab selection

- src/css/tabButtons.styl
- src/js/actions/MapActions.js
- src/js/components/TabPanel/TabButtons.js
- src/js/stores/MapStore.js
- src/js/utils/analysisUtils.js
* [Build with appid here](http://alpha.blueraster.io/gfw-mapbuilder/wait-for-geostore/?appid=6a87c5ca64df489ab2c6ac71f3b34337)
> disable analysis tab when waiting for geom to register

- src/js/languages.js
* [build with appid](http://alpha.blueraster.io/gfw-mapbuilder/726-fires-analysis/?appid=ecc2ce19175b46b094f0c31567d945f1)
> update fires analysis to include VIIRS/MODIS for supported languages

- src/js/components/LayerPanel/LossControls.js
- src/js/layers/EsriTileCanvasBase.js
- src/js/layers/TreeCoverLossLayer.js
- src/resources.js
* [Build here](http://alpha.blueraster.io/gfw-mapbuilder/702-loss-tcd/)
> fix loss layer updating with tcd change

- src/css/report.styl
- src/js/components/AnalysisPanel/Analysis.js
- src/js/components/AnalysisPanel/CarbonChart.js
- src/js/components/LayerPanel/LayerPanel.js
- src/js/report/report.js
- src/js/utils/charts.js
- src/report.jade
- src/resources.js
* [Build with changes](http://alpha.blueraster.io/gfw-mapbuilder/landmark-new-radio-buttons)
_Note_: this PR also includes an update for opening a layerGroup accordion on startup if it has layers that are active
> Landmark report - add carbon analysis

- src/js/components/LayerPanel/LayerTransparency.js
- src/js/components/LegendPanel/LegendPanel.js
- src/js/components/LegendPanel/WebMapLegend.js
- src/js/report/report.js
- src/js/stores/MapStore.js
- src/js/utils/params.js
* [build to test this change](http://alpha.blueraster.io/gfw-mapbuilder/landmark-new-radio-buttons/)
_Note_: This also addresses the issue where some layers were not visible on the report.
> Landmark legend transparency and visible report layers

- src/js/actions/MapActions.js
- src/js/components/Map.js
- src/js/constants/LandMarkConstants.js
- src/js/report/report.js
- src/resources.js
* [Build with new changes](http://alpha.blueraster.io/gfw-mapbuilder/landmark-new-radio-buttons/)
> Landmark meeting requests

- .gitignore
- src/js/layers/EsriTileCanvasBase.js
- src/js/layers/TreeCoverLossLayer.js
* [Build to test this here](http://alpha.blueraster.io/gfw-mapbuilder/712-tcloss-report/)
> fix tree cover loss not showing in report

- src/js/components/LayerPanel/LayerTransparency.js
* [Build to test change](http://alpha.blueraster.io/gfw-mapbuilder/721-transparency-ie/)
> fix layer transparency in IE

- .gitignore
- src/js/components/LayerPanel/LossControls.js
- src/js/components/Map.js
* [Build to test](http://alpha.blueraster.io/gfw-mapbuilder/url-params-fix)
> Url hash firefox fix

- src/resources.js
* [ticket](https://blueraster.assembla.com/spaces/WRI_Forest_Atlas/tickets/727-resources-js-clean-up)
> remove unused bits from resources js

- src/js/report/report.js
- src/js/utils/AppUtils.js
* [Build to test here](http://alpha.blueraster.io/gfw-mapbuilder/747-report-feature-name/)
> add custom feature name in report

- src/js/components/LayerPanel/TerraIControls.js
- src/js/components/Map.js
- src/js/stores/MapStore.js
* [Build to test here](http://alpha.blueraster.io/gfw-mapbuilder/677-hash-config/)
> set default terraI dates in state

- src/js/components/Shared/ReportSubscribe.js
- src/js/utils/analysisUtils.js
> convert dates to moment and fix fires dates format

- src/js/actions/MapActions.js
This should be the last time we have to fix this
> re#780 fix rendering order

- src/js/components/LayerPanel/LossControls.js
- src/js/config.js
- src/js/stores/MapStore.js
- src/resources.js
- [Update the annual loss data](https://blueraster.assembla.com/spaces/WRI_Forest_Atlas/tickets/realtime_list?page=1&ticket=806) --> Testable on [beta](https://beta.blueraster.io/mapbuilder/806-new-loss-year/)
> 806 new loss year

- src/external.pug
- src/js/components/AnalysisPanel/Analysis.js
- src/js/components/Navigation/Navigation.js
- src/js/layers/EsriTileCanvasBase.js
- src/js/library.js
- src/js/libraryMain.js
- src/js/utils/analysisUtils.js
- src/resources.js
- [Custom Event Listener for Library Build's Subscriptions calls](https://blueraster.assembla.com/spaces/WRI_Forest_Atlas/tickets/805--ensure-event-listener-is-in-for-the-subscription-for-library-build) --> This can be checked out [here](http://atlas.kicks-ass.net/map)
- [Vega Analysis via GFW API Widgets](https://blueraster.assembla.com/spaces/WRI_Forest_Atlas/tickets/801-v1-2-0--vega-analysis-doesn--39-t-work) --> Testable on [beta](https://beta.blueraster.io/mapbuilder/805-vega-widget/index.html)
> Prenaturally premature perfectionism

- src/js/layers/GladLayer.js
- [GLAD Layer Filter](https://blueraster.assembla.com/spaces/WRI_Forest_Atlas/tickets/realtime_list?ticket=803) --> Testable on [beta](https://beta.blueraster.io/mapbuilder/803-glad-filter/)
> Glad layer updates

- src/css/analysisPanel.styl
- src/css/reportSubButtons.styl
- [Analysis Style Tweaks](https://blueraster.assembla.com/spaces/WRI_Forest_Atlas/tickets/realtime_list?ticket=802) --> Testable on [beta](https://beta.blueraster.io/mapbuilder/802-analysis-styles/)
> Analysis & Report style fixes

- src/js/components/AnalysisPanel/Analysis.js
- src/js/components/AnalysisPanel/AnalysisPanel.js
- src/js/config.js
- src/js/report/report.js
- src/js/utils/analysisUtils.js
- src/js/utils/performAnalysis.js
- [Analysis Results Diff between Report and Result Panel](https://blueraster.assembla.com/spaces/WRI_Forest_Atlas/tickets/realtime_list?page=1&ticket=804) --> Testable on [beta](https://beta.blueraster.io/mapbuilder/804-analysis-results-diff/)
- [Analysis on Webmap Features Failure](https://blueraster.assembla.com/spaces/WRI_Forest_Atlas/tickets/realtime_list?page=1&ticket=791) --> Testable on [beta](https://beta.blueraster.io/mapbuilder/791-analysis-fix/?appid=4ea3bd32785944dd9cbd539c686a8b7c)
> Viirs analysis fixes

- src/js/components/LegendPanel/LegendPanel.js
- src/resources.js
- [Extra Layers Legend Fix](https://blueraster.assembla.com/spaces/WRI_Forest_Atlas/tickets/realtime_list?page=1&ticket=789) --> Testable on [beta](https://beta.blueraster.io/mapbuilder/789-legend-extra-group/)
> 789 extra layer legend

- src/index.pug
- src/js/library.js
- src/js/libraryMain.js
- src/js/main.js
- src/report.pug
http://beta.blueraster.io/mapbuilder/eth_restoration_121_v9.html --> External build that hits our updated lib build with a fun constructor
> load css assets in library, fix vega.min regex issue

- src/js/components/Map.js
- src/js/config.js
- src/js/utils/layerInfoCache.js
- [Layers Jumping Fix](https://app.assembla.com/spaces/WRI_Forest_Atlas/tickets/realtime_list?page=1&ticket=809) --> Testable on [beta](https://beta.blueraster.io/mapbuilder/809-layers-jumping/) 
annnd
- [Metadata also jumping for some reason](https://app.assembla.com/spaces/WRI_Forest_Atlas/tickets/realtime_list?page=1&ticket=816)
> Layer rendering order

- src/js/utils/AppUtils.js
- src/report.pug
- webpack.lib.common.js
ticket #249 
Test library build file locations and functionality here: http://beta.blueraster.io/mapbuilder/249-update-pathing/lib-build/external.html
Test and make sure regular build process still works as expected:  http://beta.blueraster.io/mapbuilder/249-update-pathing/build/
> Changes location of report and resources files for lib-build

- src/js/actions/MapActions.js
Addresses issue #256 of course!
> Ensuring we only re-order our layerPanel layers on 1st map

- src/js/utils/layerInfoCache.js
> Updated metadata layer calls

- src/js/components/LegendPanel/LegendPanel.js
- src/js/helpers/LayersHelper.js
> Updated scale-dependency check for AGOL-hosted items

- src/js/actions/MapActions.js
Fixes the second problem (our 2nd Group: Land Use, is now ordered incorrectly) that @csphang found  in #256
> 256 layer order translates

- cypress/integration/test_spec.js
- cypress/integration/ui-workflows.js
- src/js/config.js
- src/js/utils/layerInfoCache.js
This PR addresses #260 right [here](https://beta.blueraster.io/mapbuilder/219-metadata-remix/external.html?appid=f369d487979b42ff9afec4c25a2962ed) and #219 right [here](https://beta.blueraster.io/mapbuilder/219-metadata-remix/external.html)
> 219 metadata remix

- cypress/integration/test_spec.js
- cypress/integration/ui-workflows.js
- src/js/report/report.js
Addresses #227 and is not reliant upon the second issue mentioned there (AKA it can be tested [here](https://beta.blueraster.io/mapbuilder/227-report-fix/external.html), now!)
> 227 report fix

- cypress/integration/test_spec.js
- src/external.pug
- src/js/components/Map.js
- src/resources.js
- tests/resources.test.js
Initial Center and Zoom of the Map Extent can now be set in our constructor params (`resources` or `library builds`)
> 263 center and zoom

- src/js/components/AnalysisPanel/Analysis.js
- src/js/components/AnalysisPanel/VegaChart.js
- src/js/utils/charts.js
Issue #261 
http://alpha.blueraster.io/gfw-mapbuilder/261-analysis-error-handling/external.html
>  Update loading, error handling for vega charts

- src/css/analysisPanel.styl
- src/css/reportSubButtons.styl
- src/js/components/AnalysisPanel/Analysis.js
Addresses issue #302 
Issue specific to apps built with CMS
Can be tested here: http://training.from-dc.com/map
> Fix scroll issue on the analysis panel

- src/js/report/report.js
- src/js/utils/AppUtils.js
> Adding a proper report sharinghost for external builds

- src/js/components/AnalysisPanel/VegaChart.js
- tests/layerInfoCache.test.js
Fixes #293 ! Testable [https://beta.blueraster.io/mapbuilder/293-vega-fix/external.html](https://beta.blueraster.io/mapbuilder/293-vega-fix/external.html)
> 293 vega hotfix

- src/external.pug
- src/js/library.js
Can be tested on this build: http://alpha.blueraster.io/gfw-mapbuilder/meta-tags-js/external.html
> Meta tag update

- src/js/components/AnalysisPanel/VegaChart.js
[Testable!](https://beta.blueraster.io/mapbuilder/293-vega-options/external.html)
> Leaving Vega chart validation up to GFW API config

- src/js/utils/AppUtils.js
- src/js/utils/analysisUtils.js
Addresses #316 and can be tested [here!](https://beta.blueraster.io/mapbuilder/316-analysis-catch/external.html)
> 316 analysis fail catch

- src/js/actions/MapActions.js
- src/js/utils/template.js
- src/resources.js
https://my.gfw-mapbuilder.org/v1.3.3/
> Fix issue with layer ordering and new api layers

- src/css/tabView.styl
Issue #331 
Can be tested here: http://alpha.blueraster.io/gfw-mapbuilder/331-info-panel-scroll/
> Sprint 5: v1.3.4 Fix issue in info panel with scroll

- src/css/layerPanel.styl
- src/external.pug
- src/js/actions/MapActions.js
- src/js/components/LayerPanel/LayerPanel.js
- src/js/components/LayerPanel/LayerVersions.js
- src/js/components/LegendPanel/WebMapFeatureLayerLegend.js
- src/js/components/Shared/ReportSubscribe.js
- src/js/report/report.js
- src/js/stores/MapStore.js
- src/js/utils/AppUtils.js
- src/js/utils/layerFactory.js
- src/resources.js
- tests/resources.test.js
Issue #303 
Link: http://alpha.blueraster.io/gfw-mapbuilder/303-layer-versions/
****NOTE: We will need to remove the layer config examples from resources & external.pug when we are finished testing since these aren't part of the default mapbuilder config.
> Sprint 5 - v1.3.4 303 Layer Versions

- src/js/utils/layerFactory.js
Adresses #347 , and is test-able on [alpha](http://alpha.blueraster.io/gfw-mapbuilder/347-popup-translations/external.html)
> Re-creating all layers from new webmap on language-toggle

- src/js/components/LayerPanel/LossControls.js
See the issue that this fixes [here!](https://github.com/wri/gfw-mapbuilder/issues/344)
> Updated loss slider playInterval calls

- src/external.pug
- src/js/components/LayerPanel/LossControls.js
- src/js/config.js
- src/resources.js
https://github.com/wri/gfw-mapbuilder/issues/351
> 351 add 2018 loss layer

- src/external.pug
- src/resources.js
https://github.com/wri/gfw-mapbuilder/issues/364
https://alpha.blueraster.io.s3.amazonaws.com/gfw-mapbuilder/364-new-primary-forest-layer/external.html
> 364 new primary forest layer

- package.json
- src/external.pug
- src/js/components/AnalysisPanel/VegaChart.js
- src/js/components/LayerPanel/FiresControls.js
- src/js/components/LayerPanel/LayerFieldFilter.js
- src/js/config.js
- src/js/report/report.js
- src/js/utils/charts.js
- src/resources.js
This PR (testable [here](https://alpha.blueraster.io.s3.amazonaws.com/gfw-mapbuilder/merge-of-286-and-299-branches/external.html)) supplants #366 as the New Power in the Charting Universe!
> Vega default analysis

- src/js/components/AnalysisPanel/Analysis.js
- src/js/components/AnalysisPanel/VegaChart.js
- src/js/utils/charts.js
#299 
https://alpha.blueraster.io.s3.amazonaws.com/gfw-mapbuilder/299-vega-support-multiple-languages/external.html
> 299 vega support multiple languages

- src/js/components/LayerPanel/LayerFieldFilter.js
Addresses issue #375 , test-able [here!](http://alpha.blueraster.io/gfw-mapbuilder/375-filter-by-attribute/external.html?l=en)
> Checking for filterValues before adding them to the <select> options

- src/js/components/LegendPanel/LegendPanel.js
> Properly avoiding a WebMapFeatureLayerLegend component when appropriate

- src/js/components/AnalysisPanel/VegaChart.js
https://github.com/wri/gfw-mapbuilder/issues/287#issuecomment-497454550
> Change download placeholder text

- src/css/analysisPanel.styl
- src/css/controlPanel.styl
- src/css/layerPanel.styl
- src/external.pug
- src/js/components/LayerPanel/FiresControls.js
- src/js/components/LayerPanel/LossControls.js
- src/js/config.js
- src/js/helpers/LayersHelper.js
- src/resources.js
https://github.com/wri/gfw-mapbuilder/issues/360
> 360 gfw fires

- src/external.pug
- src/js/components/AnalysisPanel/VegaChart.js
https://github.com/wri/gfw-mapbuilder/issues/287#issuecomment-500003258
> 287 add download feature for vega analysis charts

- package.json
- src/external.pug
- src/resources.js
This uses Richard's new configuration, removes the restoration analysis module configs, and adds in the new UUID config for VIIRS & MODIS
Richard mentioned these changes in both of these tickets:
https://github.com/wri/gfw-mapbuilder/issues/286 
https://github.com/wri/gfw-mapbuilder/issues/360
> Test build with new config

- src/js/components/AnalysisPanel/VegaChart.js
- src/js/report/ReportAnalysis.js
- src/js/report/report.js
- src/resources.js
https://github.com/wri/gfw-mapbuilder/issues/390
> 390 report chart titles

- src/js/components/AnalysisPanel/VegaChart.js
https://github.com/wri/gfw-mapbuilder/issues/395
> Retrieve chart description from API call

- src/css/modal.styl
- src/css/report.styl
- src/external.pug
- src/externalReport.pug
- src/js/components/AnalysisPanel/VegaChart.js
- src/js/components/Modals/ModalWrapper.js
- src/js/components/Modals/ShareModal.js
- src/js/report/ReportAnalysisArea.js
- src/js/report/ReportHeader.js
- src/js/reportMain.js
- src/report.pug
https://github.com/wri/gfw-mapbuilder/issues/397
> 397 share feature

- src/css/app.styl
- src/external.pug
- src/js/library.js
http://alpha.blueraster.io/gfw-mapbuilder/smoother-loading/
> Loader in library build to avoid svg flashes

- src/js/components/AnalysisPanel/VegaChart.js
#435 
http://alpha.blueraster.io/gfw-mapbuilder/435-keep-original-height-signal/
@SwampGuzzler This should be merged into #396 since I needed to build off this branch for all of the resizing widget tickets!
> 435 keep original height signal

- src/css/report.styl
- src/js/components/AnalysisPanel/VegaChart.js
This PR initializes the charts with maximum width on load. It also center aligns the badge charts now that Richard has removed the hardcoded values in the signal!
> Resize charts on load

- src/css/analysisPanel.styl
- src/css/report.styl
- src/external.pug
- src/externalReport.pug
- src/js/components/AnalysisPanel/VegaChart.js
#432 
http://alpha.blueraster.io/gfw-mapbuilder/432-download-png-style-overwritten/
> 432 download png style overwritten

- src/external.pug
- src/externalReport.pug
- src/js/report/ReportHeader.js
#437 
http://alpha.blueraster.io/gfw-mapbuilder/437-remove-header-icon/
> 437 remove header icon

- cypress/integration/test_spec.js
- src/css/report.styl
- src/external.pug
- src/externalReport.pug
- src/js/components/AnalysisPanel/Analysis.js
- src/js/components/AnalysisPanel/VegaChart.js
- src/js/report/ReportAnalysis.js
- src/js/report/report.js
- src/resources.js
- tests/analysisModules.test.js
#452 
@SwampGuzzler Once this gets merged in, it also solves #443 
Also note, this is building off of `391-adjust-chart-settings-revert` branch. This should be reviewed first before finally merging that branch into `new-report-build`!
http://alpha.blueraster.io/gfw-mapbuilder/452-update-resources-to-distinguish-chart-types/
> 452 update resources to distinguish chart types

- src/js/components/AnalysisPanel/VegaChart.js
- src/js/report/report.js
https://github.com/wri/gfw-mapbuilder/issues/471
> 471 show title of analysis when it fails

- src/css/report.styl
- src/js/components/AnalysisPanel/VegaChart.js
- src/js/report/ReportSettings.js
- src/js/report/report.js
Fixes both of these tickets: #468  & #469
> 468 and 469 white space fix

- src/external.pug
- src/externalReport.pug
- src/js/report/ReportAnalysisArea.js
- src/js/reportLibrary.js
- src/resources.js
#480 
http://alpha.blueraster.io/gfw-mapbuilder/480-error-in-edge/
> 480 error in edge

- src/js/components/AnalysisPanel/VegaChart.js
#470 -- Richard approved!
http://alpha.blueraster.io/gfw-mapbuilder/470-loading-icon-not-visible-for-TCL-analysis/
> 470 loading icon not visible for tcl analysis

- src/css/report.styl
- src/external.pug
- src/externalReport.pug
- src/js/components/AnalysisPanel/VegaChart.js
- src/js/components/Modals/ImageryModal.js
- src/js/report/ReportAnalysis.js
- src/js/report/ReportAnalysisArea.js
- src/js/report/ReportSettings.js
- src/js/report/ReportTable.js
- src/js/report/report.js
#482 
http://alpha.blueraster.io/gfw-mapbuilder/482-print-formatting-issue/
> 482 print formatting issue

- src/css/report.styl
- src/external.pug
- src/externalReport.pug
- src/js/actions/LayerActions.js
- src/js/components/AnalysisPanel/AnalysisPanel.js
- src/js/components/Map.js
- src/js/components/Shared/ReportSubscribe.js
- src/js/report/ReportAnalysisArea.js
- src/js/report/report.js
- src/js/stores/MapStore.js
- src/js/utils/AppUtils.js
- src/resources.js
> 439 new branch before merge conflicts

- src/css/modal.styl
- src/js/components/Map.js
- src/js/components/Modals/ImageryModal.js
- src/js/utils/request.js
http://alpha.blueraster.io/gfw-mapbuilder/483-satellite-imagery-update/
This is the fix for #483 after the Sentinel API had been updated. We updated our Call to their API and added a bit of error handling so we don't try to make a layer out of nothing when the calls don't come back properly.
> 483 satellite imagery update

- src/external.pug
- src/externalReport.pug
- src/js/utils/charts.js
#466 
http://alpha.blueraster.io/gfw-mapbuilder/466-tooltips/
> 466 tooltips

- src/css/report.styl
- src/external.pug
- src/externalReport.pug
- src/js/components/AnalysisPanel/VegaChart.js
See comment on #502 
Build: http://alpha.blueraster.io/gfw-mapbuilder/502-increase-header-size/
> 502 increase header size

- src/css/map.styl
- src/css/modal.styl
- src/css/report.styl
- src/external.pug
- src/externalReport.pug
- src/js/actions/MapActions.js
- src/js/components/AnalysisPanel/CustomFeatureControl.js
- src/js/components/Map.js
- src/js/components/Modals/ControlledEditModalWrapper.js
- src/js/components/Modals/CoordinatesModal.js
- src/js/components/Modals/DraggableEditModalWrapper.js
- src/js/components/Modals/EditCoordinatesModal.js
- src/js/components/TabPanel/InfoWindow.js
- src/js/components/TabPanel/TabView.js
- src/js/languages.js
- src/js/stores/MapStore.js
https://github.com/wri/gfw-mapbuilder/issues/454
http://alpha.blueraster.io/gfw-mapbuilder/new-edit-coordinates-functionality/
> New edit coordinates functionality

- src/css/modal.styl
- src/external.pug
- src/externalReport.pug
#520 
http://alpha.blueraster.io/gfw-mapbuilder/520-adjust-height-tcd-slider/
> Adjust canopy modal container styling to git rid of scrollbar

- src/css/modal.styl
- src/js/components/LayerPanel/LayerCheckbox.js
- src/js/stores/MapStore.js
> Fix tcl info modal

- src/js/components/Map.js
> Removed mismatching infowindow calls

- src/js/components/Map.js
- src/js/stores/MapStore.js
Fixes the error we saw when drawing a polygon!
> Fix error when drawing polygon

- src/js/components/AnalysisPanel/DrawTools.js
- src/resources.js
@SwampGuzzler This should be merged into our `sprint-6-base` branch! Now that the info window is turned on/off for updating when using the measurement tool, we should also make sure that we are turning on/off the infoWindow for updating when using the draw tool as well.
I noticed in the Ethiopia build, that after I drew a shape, nothing was being display in the analysis panel.
> Draw tool fix

- src/js/components/AnalysisPanel/VegaChart.js
#548 
Build: http://alpha.blueraster.io/gfw-mapbuilder/548-remove-csv-download-glad/
> 548 remove csv download glad

- src/js/report/report.js
- src/js/reportLibrary.js
- src/js/reportLibraryMain.js
This addresses #551 
The fix can confirmed in the report of these app's:
http://blueraster.teaches-yoga.com/LBR?l=en
http://blueraster.teaches-yoga.com/GEO?l=en
when you see the proper analyses at the end of each report
> Re-wrote reportLibrary to pass it params from the CMS

- src/css/analysisPanel.styl
- src/css/modal.styl
- src/external.pug
- src/externalReport.pug
#552 
Build in CMS: http://blueraster.teaches-yoga.com/CMR?l=en
> 552 coordinate tool style adjustment

- src/js/components/Map.js
- src/js/utils/request.js
http://alpha.blueraster.io/gfw-mapbuilder/488-georgia-group-load/
https://github.com/wri/gfw-mapbuilder/issues/488
> 488 georgia lang load

- src/js/stores/MapStore.js
> Response error fix in map store

- src/js/languages.js
https://github.com/wri/gfw-mapbuilder/issues/457
> Add spanish translations for draw coordinates

- src/css/analysisPanel.styl
- src/css/infoWindow.styl
- src/css/layerPanel.styl
- src/css/modal.styl
- src/css/navigation.styl
- src/css/reportSubButtons.styl
- src/external.pug
- src/externalReport.pug
- src/js/components/Modals/ConfirmModal.js
- src/js/components/Modals/SubscribeModal.js
- src/js/components/Modals/SubscriptionsModal.js
#545 
Build: http://alpha.blueraster.io/gfw-mapbuilder/545-subscription-modal-scroll/
This PR is good to review now
> Add ms overflow style rule for IE/Edge

- src/css/analysisPanel.styl
- src/css/infoWindow.styl
- src/css/tabButtons.styl
- src/external.pug
- src/externalReport.pug
- src/js/actions/MapActions.js
- src/js/components/AnalysisPanel/MeasurementTool.js
- src/js/components/Map.js
- src/js/components/TabPanel/InfoWindow.js
- src/js/components/TabPanel/TabButtons.js
- src/js/stores/MapStore.js
- src/resources.js
@SwampGuzzler This is the new PR for #461
Build: http://alpha.blueraster.io/gfw-mapbuilder/461-multiple-selected-features-redesign/
Additional Test Build: http://alpha.blueraster.io/gfw-mapbuilder/461-multiple-selected-features-georgia-build/
> 461 multiple selected features updated

- src/external.pug
- src/js/actions/LayerActions.js
- src/js/actions/MapActions.js
- src/js/components/LegendPanel/LegendPanel.js
- src/js/components/Map.js
- src/js/stores/MapStore.js
- src/resources.js
This is a fix for #348 and for Richard's comment [here](https://github.com/wri/gfw-mapbuilder/issues/348#issuecomment-538442617) which has more widespread implications that could have caused additional `share` headaches down the road so I'm glad we got to it now!
Testable on this [http://alpha.blueraster.io/gfw-mapbuilder/348-zoom-dependent-share/?appid=277b92455c6c49059a95c9129be7baf9](http://alpha.blueraster.io/gfw-mapbuilder/348-zoom-dependent-share/?appid=277b92455c6c49059a95c9129be7baf9) site with any shared combo's such as [this](http://alpha.blueraster.io/gfw-mapbuilder/348-zoom-dependent-share/?appid=277b92455c6c49059a95c9129be7baf9&x=24.42&y=-3.75&z=5&l=en&b=null&t=LAYERS&a=Cherangany_WGS_shapefile_4406_0%2CAffectation_des_terres_fr_8473&o=0.6%2C0.6)
> 348 zoom dependent share merge

- src/js/components/Map.js
- src/js/utils/basemapUtils.js
Quick fix for our basemap label visibility!
> Sprint six hot fix

- cypress/integration/agol_spec.js
- package-lock.json
- package.json
- src/css/analysisPanel.styl
- src/css/modal.styl
- src/external.pug
- src/externalReport.pug
- src/js/components/AnalysisPanel/VegaChart.js
- src/js/components/Map.js
- src/js/components/Modals/ImageryModal.js
- src/js/config.js
- src/js/library.js
- src/js/report/report.js
- src/js/reportLibrary.js
- src/js/reportLibraryMain.js
- src/js/stores/MapStore.js
- src/resources.js
- tests/apiWidgets.test.js
This contains all of the `cms` fixes that our **Dr. Develop** branch already has!
> Sprint 6 base dev merge

- src/external.pug
- src/externalReport.pug
- src/js/languages.js
#585 
Build: http://alpha.blueraster.io/gfw-mapbuilder/585-update-shapefile-text/
> 585 update shapefile text

- src/js/components/LayerPanel/AGOLBasemap.js
- src/js/components/LayerPanel/LayerPanel.js
- src/js/components/Map.js
- src/js/utils/basemapUtils.js
- src/resources.js
@KaylaKremer This is the fix for https://github.com/wri/gfw-mapbuilder/issues/318 -- it's not ready to merge until I get a proper custom basemap icon from @mandelson !
Edit: It's **Now Ready to Merge!!**
It's test-able at these 3 links for comparison:
- http://alpha.blueraster.io/gfw-mapbuilder/318-inherit-basemap/topographie/
- http://alpha.blueraster.io/gfw-mapbuilder/318-inherit-basemap/india-mask/
- http://alpha.blueraster.io/gfw-mapbuilder/318-inherit-basemap/generic/ (`useWebmapBasemap: false`)
> 318 inherit basemap

- src/css/infoWindow.styl
- src/css/modal.styl
- src/resources.js
Fixes the following issues in the CMS:
> Fix close button positioning cms

- src/js/components/AnalysisPanel/MeasurementTool.js
- src/js/components/MapControls/ControlPanel.js
Fixes #599 
Test here: http://alpha.blueraster.io/gfw-mapbuilder/measurement-multi-lang-fix/?l=en
We get an extra measurement tool
Issue Number: #599 
We don't get an extra measurement tool
> Removing any pre-existing measurement tools on new map-creation

- src/external.pug
- src/externalReport.pug
- src/js/stores/MapStore.js
- src/resources.js
- [ x] Bugfix
Issue Number: N/A
- Clears the extra VIIRS/MODIS fires layers when user selects to clear all layers
-
-
- [x ] No
Test Build: http://alpha.blueraster.io/gfw-mapbuilder/598-MODIS-VIIRS-display-after-clearing-all-layers/
> Hide additional VIIRS/MODIS fires when clear all is selected

- src/external.pug
- src/externalReport.pug
- src/js/components/LayerPanel/RadioButton.js
- src/resources.js
- [ x] Bugfix
Issue Number: #602 
- Fixed the logic handling which color to display in the radio buttons
-
-
- [x ] No
Test Build: http://alpha.blueraster.io/gfw-mapbuilder/602-radio-button-fill-color-missing/
> Fix logic for handling fill color for radio buttons

- src/external.pug
- src/externalReport.pug
- src/js/utils/layerFactory.js
- src/resources.js
- [x ] Bugfix
Issue Number: #608 
- Fixes issue of fire layers not working when switching languages
-
-
- [x ] No 
Test Build: http://alpha.blueraster.io/gfw-mapbuilder/fires-layers-creation-lang-toggle
> Fires layers creation lang toggle

- src/js/components/LayerPanel/LayerToggles.js
- src/js/helpers/LayersHelper.js
- src/js/stores/MapStore.js
- [ x] Bugfix
Issue Number: #598 
-
-
-
Build: http://alpha.blueraster.io/gfw-mapbuilder/598-MODIS-VIIRS-display-after-clearing-all-layers/
> 598 modis viirs display after clearing all layers

- src/js/actions/MapActions.js
- src/js/components/LayerPanel/LayerPanel.js
- src/js/components/Map.js
- src/js/utils/basemapUtils.js
- src/resources.js
https://github.com/wri/gfw-mapbuilder/issues/318
http://alpha.blueraster.io/gfw-mapbuilder/318-basemap-india-update/
We now re-order basemap layers as well so layers coming from the webmap that serve as basemap don't get their `order` catapulted above other standard layers
> 318 basemap india debug

- src/css/modal.styl
A fix to #616 that can be tested right back at the root [CMS url](http://blueraster.teaches-yoga.com/COG?l=en)
> Updated subscription modal to remove overflow

- src/js/actions/MapActions.js
- src/js/components/Map.js
> Inheriting default layer-viz from non-shared maps

- src/external.pug
- src/externalReport.pug
- src/js/components/TabPanel/InfoWindow.js
- src/resources.js
- [ x] Bugfix
Issue Number: #624 
- Fixed the prev/next buttons to select the features on the map!
-
-
- [x ] No
Test Build: http://alpha.blueraster.io/gfw-mapbuilder/624-next-button-bug/
> 624 next button bug

- src/css/infoWindow.styl
- [x ] Bugfix
Issue Number: #629 
- Added `align-items` CSS property so edit and delete buttons center-align with each other
-
-
> Center-align the edit and delete buttons

- src/js/components/Shared/ReportSubscribe.js
Issue Number: #630
- Fix color/thickness of border for subscribe button
- Fix flickering (still need to test in CMS to ensure it workes there)
-
- [ x ] No
Test Build: http://alpha.blueraster.io/gfw-mapbuilder/subscribe-button-fix/
> Subscribe button fix

- package.json
Tests Fail ):    --> But only in CircleCI's odd `Chrome` emulation!
- Tests pass!
> Cypress e2e on default, not chrome

- src/css/report.styl
- src/external.pug
- src/externalReport.pug
- src/js/components/AnalysisPanel/VegaChart.js
- src/js/report/ReportTable.js
- src/js/report/report.js
- src/resources.js
- [x ] Bugfix
Issue Number: #628 
- We now check to see if the url for the attribute data table contains 'dynamicLayer'. If so, we intervene and set the url to go to the map server instead with the layer's id.
- Also fixes toggle color issue in the report as pointed out by Richard!
-
- [x ] No
Test Build: http://alpha.blueraster.io/gfw-mapbuilder/no-attribute-table-cameroon/
> No attribute table cameroon

- src/external.pug
- src/externalReport.pug
- src/js/components/Modals/SearchModal.js
- src/js/components/TabPanel/InfoWindow.js
- src/js/utils/analysisUtils.js
- src/resources.js
- [ x] Bugfix
Issue Number: #612 
- Add additional checks to previous/next buttons when cycling through selected features
-
-
- [ x] No
Build: http://alpha.blueraster.io/gfw-mapbuilder/612-search-info-window/
> 612 search info window

- src/js/components/Map.js
Fixes Issue #621 which can be tested, of course, on [alpha](http://alpha.blueraster.io/gfw-mapbuilder/621-share-layer/)
> Hiding and showing webmap layers on-share

- src/js/components/Map.js
Fixes #652 and can be tested [here](http://alpha.blueraster.io/gfw-mapbuilder/652-correct-zoom/?l=en)
> Language-change after setExtent on share

- src/js/components/LayerPanel/LossControls.js
> TCL share check for layer existence

- src/js/report/ReportTable.js
http://alpha.blueraster.io/gfw-mapbuilder/628-report-table-grg/
> Grabbing layerId from sublayers for report table

- src/external.pug
- src/externalReport.pug
- src/js/components/Navigation/LanguageToggle.js
- src/js/components/TabPanel/InfoWindow.js
- src/resources.js
Issue Number: #660 
- Clears selected features and changes tab when user toggles language
-
-
Test Build: http://alpha.blueraster.io/gfw-mapbuilder/660-language-toggle/
> 660 language toggle

- src/js/components/LayerPanel/LossControls.js
- src/js/components/Modals/CanopyModal.js
- src/js/layers/EsriTileCanvasBase.js
#673 workflow 2
--> We know about the TCL pixel issue but this updates the base URL definition and the TreeCover layer properly
> 673 english load

- src/js/actions/MapActions.js
- src/js/layers/EsriTileCanvasBase.js
- src/js/layers/TreeCoverLossLayer.js
#673 
http://alpha.blueraster.io/gfw-mapbuilder/673-share-treecover/drc.html
http://alpha.blueraster.io/gfw-mapbuilder/673-share-treecover/cmr.html
http://alpha.blueraster.io/gfw-mapbuilder/673-share-treecover/grg.html
http://alpha.blueraster.io/gfw-mapbuilder/673-share-treecover/index.html
> 673 share treecover

- src/js/layers/GFWImageryLayer.js
#673 --> reminiscent of #681 !
> Properly cancelling outdated GFW Imagery requests

- src/js/layers/EsriTileCanvasBase.js
#673 --> reminiscent of #681 and #682 !
> Removing duplicate imagery in canvas-creation

- src/external.pug
- src/externalReport.pug
> Committing prod configurations

- src/js/controllers/mapController.ts
- Integrated ESRI legend widget (out of the box) in `mapController.ts`
> ESRI Legend widget

- configs/cameroon.js
- src/css/header.scss
- src/css/index.scss
- src/js/components/App.tsx
- src/js/components/header/Header.tsx
- src/js/components/header/LanguageDropdown.tsx
- Integrated `<Header/>` component to render in `App.tsx`
- `Header.tsx` renders URL, logo, title and subtitle. Also renders `<LanguageDropdown/>`
- `LanguageDropdown.tsx` leverages `a11y` best practices to render a non-styled dropdown
- `header.scss` styles (look less than 10 minutes) everything in the Header component
- updated `.mapview-container` to account for header height so mapview doesn't render over the header while tabbing
> Header component

- src/resources.js
> Prod header logo link update

- .eslintrc.js
- package-lock.json
- package.json
- Integrated `eslint-plugin-jsx-a11y` to track and ID accessibility issues
- Followed guidance provided at [npmjs.com](https://www.npmjs.com/package/eslint-plugin-jsx-a11y)
- _Please note;_ I've decided to enable all recommendations so we can ensure we're getting a comprehensive understanding of how well we've implemented `a11y` recommendations. If that's not a good fit, I can configure a list of recommended rules.
> eslint a11y module

- src/js/components/header/LanguageDropdown.tsx
- src/js/components/mapWidgets/penWidget.tsx
- src/js/components/mapWidgets/printWidget.tsx
- src/js/components/mapWidgets/searchWidget.tsx
- src/js/components/mapWidgets/shareWidget.tsx
- src/js/components/modal/modalCard.tsx
- src/js/store/appState/actions.ts
- src/js/store/appState/reducers.ts
- src/js/store/appState/types.ts
- Update made to the `appState` store to make all properties required instead of all properties being optional
- `actions.js` and `reducers.js` target a specific **slice** of `appState` meaning that we can have required state properties and can dispatch actions with more clarity (examples in widget components)
- changes made to widget comps, modal and lang picker to reflect new action pattern.
> Redux appstate precision changes
